---
title: "Scrape"
author: "Cole Monson"
date: "2024-05-08"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

library(shiny)
library(DT)


library(mdsr)

library(tidyverse)


studyabroad <- read_csv("studyabroad.csv") |> select(-`...1`)

```

```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

```{r, eval=FALSE}
# play zone! Here we try to replicate initial plot using ggplot




```

```{r}
inputPanel(
  
  sliderInput("num_adjust", label = "Number of Countries:",
              min = 5, max = 20, value = 1, step = 1)
)

renderPlot(studyabroad |>
  group_by(country) |>
  summarize(n = n()) |>
  mutate(country = fct_reorder(country, n)) |>
  slice_max(country, n = as.numeric(input$num_adjust)) |>
  ggplot(aes(x = country, y = n)) +
  geom_col(fill = "red") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country", y = "Num Occurrences", title = "Most Frequently Offered Destinations"))
```

```{r}
  studyabroad |>
  group_by(country) |>
  summarize(n = n()) |>
  mutate(country = fct_reorder(country, n)) |>
  slice_max(country, n = 10) |>
  ggplot(aes(x = country, y = n)) +
  geom_col(fill = "red") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country", y = "Num Occurrences", title = "Most Frequently Offered Destinations")
```

```{r}
studyabroad |>
  # we won't use mWorldMap often, but it's a good quick illustration
  mosaic::mWorldMap(key = "country") +
  geom_polygon(aes(fill = equality_index), color = "black") + 
  #scale_fill_brewer("Oil Prod. (bbl/day)", na.value = "white") +
  theme(legend.position = "top")
```

```{r}
library(tidyverse)
library(highcharter)

data(worldgeojson, package = "highcharter")

hc <- highchart() %>%
  hc_add_series_map(
    worldgeojson, studyabroad, value = "equality_index", joinBy = c('name','country'),
    name = "equality_index"
    )  %>% 
  hc_colorAxis(stops = color_stops()) %>% 
  hc_title(text = "World Map") %>% 
  hc_subtitle(text = "Life Expectancy in 2015")

hc
```



```{r}
library(tidyverse)
library(highcharter)

options(highcharter.theme = hc_theme_smpl(tooltip = list(valueDecimals = 2)))

data(worldgeojson, package = "highcharter")

hc <- highchart() %>%
  hc_add_series_map(
    worldgeojson, studyabroad, value = "equality_index", joinBy = c('name','country'),
    name = "Equality Index"
    )  %>% 
  hc_colorAxis(stops = color_stops()) %>% 
  hc_title(text = "Equality Index in St. Olaf Study Abroad Programs") %>% 
  hc_subtitle(text = "St. Olaf Study Abroad Program Locations")

hc

```

```{r}
ui <- fluidPage(
  titlePanel("Sortable Table"),
  sidebarLayout(
    sidebarPanel(
      selectInput("order_by", "Order by:", choices = c("Equality Index", "Legal Index", "Public Opinion Index")),
       radioButtons("order_dir", "Order direction:", choices = c("Ascending", "Descending"))
    ),
    mainPanel(
      DTOutput("table")
    )
  )
)

server <- function(input, output) {
  output$table <- renderDT({
    order_dir <- ifelse(input$order_dir == "Ascending", TRUE, FALSE)
    ordered_indecies <- switch(input$order_by,
                           "Equality Index" = studyabroad[order(studyabroad$equality_index), ],
                           "Legal Index" = studyabroad[order(studyabroad$legal_index), ],
                           "Public Opinion Index" = studyabroad[order(studyabroad$public_opinion_index), ])

    datatable(ordered_indecies, options = list(ordering = TRUE))
  })
}

shinyApp(ui = ui, server = server)
```

