---
title: "Scrape"
author: "Siri Sagedahl"
date: "2024-05-04"
output: html_document
---

```{r}
library(tidyverse)
library(stringr)
library(rvest)
library(httr)
library(janitor)
```


```{r}
robotstxt::paths_allowed("https://www.equaldex.com/equality-index")

robotstxt::paths_allowed("https://stolaf.studioabroad.com/index.cfm?FuseAction=Programs.ListAll&type=1")
```

```{r}
equaldex <- read_html("https://www.equaldex.com/equality-index")

tables2 <- html_nodes(equaldex, css = "table") 

html_table(tables2, header = TRUE, fill = TRUE)

equality <- html_table(tables2, header = TRUE, fill = TRUE)[[5]]
```


```{r}
studyabroad <- read_html("https://stolaf.studioabroad.com/index.cfm?FuseAction=Programs.ListAll&type=1")

tables3 <- html_nodes(studyabroad, css = "table") 

html_table(tables3, header = TRUE, fill = TRUE)

studyabroad <- html_table(tables3, header = TRUE, fill = TRUE)[[1]]
```
```{r}
continent <- read_html("https://www.equaldex.com/equality-index")

tables2 <- html_nodes(equaldex, css = "table") 

html_table(tables2, header = TRUE, fill = TRUE)

continent <- html_table(tables2, header = TRUE, fill = TRUE)[[1]]
```

```{r}
#studyabroad cleaning
studyabroad <- clean_names(studyabroad)
studyabroad$city <- str_replace_all(studyabroad$city, "(\t){1,}", "")
studyabroad$country <- str_replace_all(studyabroad$country, "(\t){1,}", "")
studyabroad$region <- str_replace_all(studyabroad$region, "(\t){1,}", "")
studyabroad$duration <- ifelse(studyabroad$save_share == "Save this program", "J-term", "Semester")
```

```{r}
studyabroad_t <- studyabroad |>
  select(program_name,
         duration)
```

```{r}
studyabroad <- separate_rows(studyabroad, city, country, region, sep = "\n")
studyabroad <- studyabroad |>
  group_by(program_name) |>
  mutate(city_id = row_number()) |>
  ungroup()
studyabroad <- studyabroad |>
  group_by(program_name, city) |>
  summarize(country = first(country),
            region = first(region),
            .groups = "drop")
```

```{r}
#equality equality
equality <- clean_names(equality)
equality$public_opinion_index <- str_replace_all(equality$public_opinion_index, "â.", "50")
equality$country <- str_remove_all(equality$country, "[\\d\\d. ]")
equality$country <- str_replace_all(equality$country, "([a-z]+)([A-Z])", "\\1 \\2")
```

```{r}
continent <- rbind(colnames(continent), continent)
colnames(continent) <- c("cont", "equality_cont", "legal_cont", "po_cont")
continent$cont <- str_remove_all(continent$cont, " \\d.*")
```

```{r}
studyabroad <- studyabroad |>
  inner_join(continent, join_by(region == cont)) |>
  left_join(equality) |>
  left_join(studyabroad_t)
```



```{r}
write.csv(studyabroad, file = "studyabroad.csv")
```

